spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: bootuser
    password: bootuser
    url: jdbc:mariadb://localhost:3308/albamon

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 10
        format_sql: true
    open-in-view: true

  profiles:
    active: local

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
